#!/bin/sh

# Runs code generation. Use: "./generate" or "./generate watch" in project dir.
if [[ $1 == "codegen" ]]; then
    if [[ $2 == "watch" ]]; then
        flutter pub run build_runner watch --delete-conflicting-outputs
    else
        flutter pub run build_runner build --delete-conflicting-outputs
    fi
fi

if [[ $1 == "genl10n" ]]; then
    flutter gen-l10n
fi